CREATE DATABASE DB_CONSTRUINDO_VIDAS;

USE DB_CONSTRUINDO_VIDAS;

CREATE TABLE TB_CATEGORIA(
ID BIGINT (5) AUTO_INCREMENT,
CATEGORIA VARCHAR(255) NOT NULL,
PRECO FLOAT (6,2) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE TB_PRODUTOS (
ID BIGINT(5) AUTO_INCREMENT,
DEPARTAMENTO VARCHAR (255) NOT NULL,
NOME VARCHAR(255),
DESCRICAO VARCHAR(255),
CATEGORIA_ID BIGINT,
PRIMARY KEY (ID),
FOREIGN KEY (CATEGORIA_ID) REFERENCES TB_CATEGORIA (ID)
);

INSERT INTO TB_CATEGORIA (CATEGORIA, PRECO)
VALUES ("PINTURA", 30.00);
INSERT INTO TB_CATEGORIA (CATEGORIA, PRECO)
VALUES ("ENCANAMENTO", 10.00);
INSERT INTO TB_CATEGORIA (CATEGORIA, PRECO)
VALUES ("ELETRICIDADE", 150.90);
INSERT INTO TB_CATEGORIA (CATEGORIA, PRECO)
VALUES ("PISO", 20.90);
INSERT INTO TB_CATEGORIA (CATEGORIA, PRECO)
VALUES ("REVESTIMENTO", 35.90);


SELECT * FROM TB_CATEGORIA;

INSERT INTO TB_PRODUTOS (DEPARTAMENTO, NOME,DESCRICAO, CATEGORIA_ID)
VALUES ("PINTURA", "TINTA", "OLEO", 1);
INSERT INTO TB_PRODUTOS (DEPARTAMENTO, NOME,DESCRICAO, CATEGORIA_ID)
VALUES ("PINTURA", "PINCEL", "GRANDE", 2);
INSERT INTO TB_PRODUTOS (DEPARTAMENTO, NOME,DESCRICAO, CATEGORIA_ID)
VALUES ("PINTURA", "MASSA CORRIDA", "ACRILINA", 3);
INSERT INTO TB_PRODUTOS (DEPARTAMENTO, NOME,DESCRICAO, CATEGORIA_ID)
VALUES ("ELETRECIDADE", "LUSTRE", "CRISTAL", 1);
INSERT INTO TB_PRODUTOS (DEPARTAMENTO, NOME,DESCRICAO, CATEGORIA_ID)
VALUES ("ELETRECIDADE", "FIO", "COBRE", 2);
INSERT INTO TB_PRODUTOS (DEPARTAMENTO, NOME,DESCRICAO, CATEGORIA_ID)
VALUES ("ELETRECIDADE", "TOMADA", "TIPO C", 3);
INSERT INTO TB_PRODUTOS (DEPARTAMENTO, NOME,DESCRICAO, CATEGORIA_ID)
VALUES ("PISO", "LAMINADO", "MARROM", 1);
INSERT INTO TB_PRODUTOS (DEPARTAMENTO, NOME,DESCRICAO, CATEGORIA_ID)
VALUES ("REVESTIMENTO", "PAPEL DE PAREDE", "3D", 2);

SELECT * FROM TB_PRODUTOS;

SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIA WHERE PRECO > 100;
SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIA WHERE PRECO >= 70 AND PRECO <= 150;
SELECT * FROM TB_PRODUTOS WHERE NOME LIKE "%C%";
SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIA ON TB_PRODUTOS.CATEGORIA_ID = TB_CATEGORIA.ID;
SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIA ON TB_PRODTOS.CATEGORIA_ID = TB_CATEGORIA.ID
WHERE CATEGORIA_ID = 3;