CREATE DATABASE DB_CURSO_DA_MINHA_VIDA;

USE DB_CONSTRUINDO_VIDAS;

CREATE TABLE TB_CATEGORIA(
ID BIGINT (5) AUTO_INCREMENT,
CATEGORIA VARCHAR(255) NOT NULL,
PRECO FLOAT (6,2) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE TB_PRODUTOS (
ID BIGINT(5) AUTO_INCREMENT,
CURSO VARCHAR (255) NOT NULL,
NOME VARCHAR(255),
DESCRICAO VARCHAR(255),
CATEGORIA_ID BIGINT,
PRIMARY KEY (ID),
FOREIGN KEY (CATEGORIA_ID) REFERENCES TB_CATEGORIA (ID)
);

INSERT INTO TB_CATEGORIA (CATEGORIA, PRECO)
VALUES ("CIENCIAS DA SAUDE", 3000.00);
INSERT INTO TB_CATEGORIA (CATEGORIA, PRECO)
VALUES ("EXATAS", 800.00);
INSERT INTO TB_CATEGORIA (CATEGORIA, PRECO)
VALUES ("HUMANAS", 900.00);
INSERT INTO TB_CATEGORIA (CATEGORIA, PRECO)
VALUES ("TECNICO", 150.00);


SELECT * FROM TB_CATEGORIA;

INSERT INTO TB_PRODUTOS (DEPARTAMENTO, NOME,DESCRICAO, CATEGORIA_ID)
VALUES ("EXATAS", "ENG.PRODUCAO", "5 ANOS", 1);
INSERT INTO TB_PRODUTOS (DEPARTAMENTO, NOME,DESCRICAO, CATEGORIA_ID)
VALUES ("EXATAS", "ENG.NAVAL", "5 ANOS", 2);
INSERT INTO TB_PRODUTOS (DEPARTAMENTO, NOME,DESCRICAO, CATEGORIA_ID)
VALUES ("EXATAS", "ARQUITETURA", "4 ANOS", 3);
INSERT INTO TB_PRODUTOS (DEPARTAMENTO, NOME,DESCRICAO, CATEGORIA_ID)
VALUES ("CIENCIA DAS SAUDE", "MEDICINA", "6 ANOS", 1);
INSERT INTO TB_PRODUTOS (DEPARTAMENTO, NOME,DESCRICAO, CATEGORIA_ID)
VALUES ("CIENCIA DA SAUDE", "ENFERMAGEM", "5 ANOS", 2);
INSERT INTO TB_PRODUTOS (DEPARTAMENTO, NOME,DESCRICAO, CATEGORIA_ID)
VALUES ("CIENCIA DA SAUDE", "FISIOTERAPIA", "4 ANOS", 3);
INSERT INTO TB_PRODUTOS (DEPARTAMENTO, NOME,DESCRICAO, CATEGORIA_ID)
VALUES ("CENCIAS HUMANAS", "DIREIRO", "5 ANOS", 1);
INSERT INTO TB_PRODUTOS (DEPARTAMENTO, NOME,DESCRICAO, CATEGORIA_ID)
VALUES ("TECNICO", "TECNICO DE ENFERMAGEM", "2 ANOS", 2);

SELECT * FROM TB_PRODUTOS;

SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIA WHERE PRECO > 500;
SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIA WHERE PRECO >= 600 AND PRECO <= 1000;
SELECT * FROM TB_PRODUTOS WHERE NOME LIKE "%J%";
SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIA ON TB_PRODUTOS.CATEGORIA_ID = TB_CATEGORIA.ID;
SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIA ON TB_PRODTOS.CATEGORIA_ID = TB_CATEGORIA.ID
WHERE CATEGORIA_ID = 3;