CREATE DATABASE DB_FARMACIA_BEM_ESTAR;

USE DB_PIZZARIA_LEGAL;

CREATE TABLE TB_CATEGORIA(
ID BIGINT (5) AUTO_INCREMENT,
CATEGORIA VARCHAR(255) NOT NULL,
PRECO FLOAT (6,2) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE TB_PRODUTOS (
ID BIGINT(5) AUTO_INCREMENT,
DEPARTAMENTO VARCHAR (255) NOT NULL,
NOME VARCHAR(255),
DESCRICAO VARCHAR(255),
CATEGORIA_ID BIGINT,
PRIMARY KEY (ID),
FOREIGN KEY (CATEGORIA_ID) REFERENCES TB_CATEGORIA (ID)
);

INSERT INTO TB_CATEGORIA (CATEGORIA, PRECO)
VALUES ("MEDICAMENTO", 99.90);
INSERT INTO TB_CATEGORIA (CATEGORIA, PRECO)
VALUES ("CÓSMETICO", 70.90);
INSERT INTO TB_CATEGORIA (CATEGORIA, PRECO)
VALUES ("VITAMINAS", 15.90);
INSERT INTO TB_CATEGORIA (CATEGORIA, PRECO)
VALUES ("ALIMENTOS", 2.90);

SELECT * FROM TB_CATEGORIA;

INSERT INTO TB_PRODUTOS (DEPARTAMENTO, NOME,DESCRICAO, CATEGORIA_ID)
VALUES ("HIGIENE PESSOAL", "SABONETE", "PARA PELE OLEOSA", 1);
INSERT INTO TB_PRODUTOS (DEPARTAMENTO, NOME,DESCRICAO, CATEGORIA_ID)
VALUES ("HIGIENE PESSOAL", "SHAMPOO", "CABELOS LISOS", 2);
INSERT INTO TB_PRODUTOS (DEPARTAMENTO, NOME,DESCRICAO, CATEGORIA_ID)
VALUES ("HIGIENE PESSOAL", "CONDICIONADOR", "COBELOS ENROLDOS", 3);
INSERT INTO TB_PRODUTOS (DEPARTAMENTO, NOME,DESCRICAO, CATEGORIA_ID)
VALUES ("ALIMENTOS", "BARRA SE SEREAL", "CHOCOLATE AO LEITE!", 1);
INSERT INTO TB_PRODUTOS (DEPARTAMENTO, NOME,DESCRICAO, CATEGORIA_ID)
VALUES ("ALIMENTOS", "MENTOS", "SABOR MORANGO!", 2);
INSERT INTO TB_PRODUTOS (DEPARTAMENTO, NOME,DESCRICAO, CATEGORIA_ID)
VALUES ("ALIMENTOS", "LEITE NINHO", "SEM LACTOSE!", 3);
INSERT INTO TB_PRODUTOS (DEPARTAMENTO, NOME,DESCRICAO, CATEGORIA_ID)
VALUES ("COSMETICO", "PERFUME", "FEMININO", 1);
INSERT INTO TB_PRODUTOS (DEPARTAMENTO, NOME,DESCRICAO, CATEGORIA_ID)
VALUES ("COSMETICO", "PERFUME", "MASCULINO!", 2);

SELECT * FROM TB_PRODUTOS;

SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIA WHERE PRECO > 50;
SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIA WHERE PRECO >= 5 AND PRECO <= 60;
SELECT * FROM TB_PRODUTOS WHERE NOME LIKE "%C%";
SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIA ON TB_PRODUTOS.CATEGORIA_ID = TB_CATEGORIA.ID;
SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIA ON TB_PRODTOS.CATEGORIA_ID = TB_CATEGORIA.ID
WHERE CATEGORIA_ID = 1;