CREATE DATABASE DB_PIZZARIA_LEGAL;

USE DB_PIZZARIA_LEGAL;

CREATE TABLE TB_CATEGORIAS(
ID BIGINT (5) AUTO_INCREMENT,
TAMANHO VARCHAR(255) NOT NULL,
PRECO FLOAT (6,2) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE TB_PIZZAS (
ID BIGINT(5) AUTO_INCREMENT,
SABOR VARCHAR (255) NOT NULL,
INGREDIENTES VARCHAR(255),
DESCRICAO VARCHAR(255),
CATEGORIA_ID BIGINT,
PRIMARY KEY (ID),
FOREIGN KEY (CATEGORIA_ID) REFERENCES TB_CATEGORIAS (ID)
);

INSERT INTO TB_CATEGORIAS (TAMANHO, PRECO)
VALUES ("GRANDE", 99.90);
INSERT INTO TB_CATEGORIAS (TAMANHO, PRECO)
VALUES ("MÉDIA", 70.90);
INSERT INTO TB_CATEGORIAS (TAMANHO, PRECO)
VALUES ("PEQUENA", 29.90);
INSERT INTO TB_CATEGORIAS (TAMANHO, PRECO)
VALUES ("BROTINHO", 10.90);
INSERT INTO TB_CATEGORIAS (TAMANHO, PRECO)
VALUES ("GIGANTE", 199.90);

SELECT * FROM TB_CATEGORIAS;

INSERT INTO TB_PIZZAS (SABOR, INGREDIENTES,DESCRICAO, CATEGORIA_ID)
VALUES ("MARGUERITA", "QUEIJO, MOLHO DE TOMATE, AZEITE,MARNJERICAO", "COM BASTANTE QUEIJO", 1);
INSERT INTO TB_PIZZAS (SABOR, INGREDIENTES,DESCRICAO, CATEGORIA_ID)
VALUES ("MARGUERITA", "QUEIJO, MOLHO DE TOMATE, AZEITE,MARNJERICAO", "COM BASTANTE QUEIJO", 2);
INSERT INTO TB_PIZZAS (SABOR, INGREDIENTES,DESCRICAO, CATEGORIA_ID)
VALUES ("MARGUERITA", "QUEIJO, MOLHO DE TOMATE, AZEITE,MARNJERICAO", "COM BASTANTE QUEIJO", 3);
INSERT INTO TB_PIZZAS (SABOR, INGREDIENTES,DESCRICAO, CATEGORIA_ID)
VALUES ("DOCE", "CHOCOLATE BRANCO, GRANULADO", "CHOCOLATE AO LEITE!", 1);
INSERT INTO TB_PIZZAS (SABOR, INGREDIENTES,DESCRICAO, CATEGORIA_ID)
VALUES ("BRIGADEIRO", "CHOCOLATE COM CONDENSADO, GRANULADO", "SEM LACTOSE!", 2);
INSERT INTO TB_PIZZAS (SABOR, INGREDIENTES,DESCRICAO, CATEGORIA_ID)
VALUES ("PRESTIGIO", "CHOCOLATE COM COCO, CHOCOLATE AO LEITE,BRIGADEIRO DE COCO", "BEM RECHEADO!", 2);
INSERT INTO TB_PIZZAS (SABOR, INGREDIENTES,DESCRICAO, CATEGORIA_ID)
VALUES ("DOPARA", "JAMBU, CAMARAO, MOLHO DE TUCUPI", "BEM PARAENSE!", 1);
INSERT INTO TB_PIZZAS (SABOR, INGREDIENTES,DESCRICAO, CATEGORIA_ID)
VALUES ("3 QUEIJOS", "PROVOLONE, CHEDDAR, GORGONZOLA", "PURO QUEIJO!", 2);

SELECT * FROM TB_PIZZAS;

SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS WHERE PRECO > 45;
SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS WHERE PRECO >= 50 AND PRECO <= 100;
SELECT * FROM TB_PIZZAS WHERE NOME LIKE "%C%";
SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS ON TB_PIZZAS.CATEGORIA_ID = TB_CATEGORIAS.ID;
SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS ON TB_PIZZAS.CATEGORIA_ID = TB_CATEGORIAS.ID
WHERE CATEGORIA_ID = 3;