CREATE DATABASE DB_SERVICO_RH;

USE DB_SERVICO_RH;

CREATE TABLE TB_FUNCIONARIOS(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR (1000),
IDADE INT,
FUNCAO CHAR(255),
ENDERECO VARCHAR(1000),
SALARIO DECIMAL NOT NULL,
PRIMARY KEY(ID)
);

INSERT INTO TB_FUNCIONARIOS (NOME, IDADE, FUNCAO, ENDERECO, SALARIO)
VALUES ("LEANDRO", 28, "DEV SENIOR", "RUA ANASTACIO", 7000);
INSERT INTO TB_FUNCIONARIOS (NOME, IDADE, FUNCAO, ENDERECO, SALARIO)
VALUES ("LUIZA", 22, "DEVA JUNIOR", "RUA NAZARE", 1000);
INSERT INTO TB_FUNCIONARIOS (NOME, IDADE, FUNCAO, ENDERECO, SALARIO)
VALUES ("SILVIA", 27, "DEVA PLENO", "RUA PEDRO MIRANDA", 5000);

SELECT * FROM TB_FUNCIONARIOS;

select * FROM TB_FUNCIONARIOS WHERE SALARIO > 2000;

select * FROM TB_FUNCIONARIOS WHERE SALARIO < 2000; 

SET SQL_SAFE_UPDATES = 0; 

